### ISSUE TITLE
test failure on clean clone

### ISSUE THREAD

**Issue by kumavis** [ConsenSys/blockapps-web3#3]
```
╭─kumavis@xyzs-MacBook-Pro  ~/dev/blockapps-web3 ‹node-v0.12.7›  (master) 
╰─$ truffle build              
Completed without errors on Thu Oct 01 2015 13:14:16 GMT-0700 (PDT)
╭─kumavis@xyzs-MacBook-Pro  ~/dev/blockapps-web3 ‹node-v0.12.7›  (master) 
╰─$ truffle test 
Using environment test.


  Contract: Example
    1) "before all" hook: redeploy before each contract


  0 passing (2s)
  1 failing

  1) Contract: Example "before all" hook: redeploy before each contract:
     Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.callback (node_modules/web3/lib/web3/contract.js:144:36)
    at node_modules/web3/lib/web3/method.js:165:21
    at node_modules/web3/lib/web3/requestmanager.js:101:20
    at /Users/kumavis/dev/blockapps-web3/app/blockapps-web3.es6:251:11
    at /Users/kumavis/dev/blockapps-web3/app/blockapps-web3.es6:647:13
    at XMLHttpRequest.onreadystatechange (/Users/kumavis/dev/blockapps-web3/app/blockapps-web3.es6:334:15)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/kumavis/dev/blockapps-web3/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/kumavis/dev/blockapps-web3/node_modules/xhr2/lib/xhr2.js:353:12)
    at XMLHttpRequest._onHttpResponseEnd (/Users/kumavis/dev/blockapps-web3/node_modules/xhr2/lib/xhr2.js:507:12)
    at IncomingMessage.<anonymous> (/Users/kumavis/dev/blockapps-web3/node_modules/xhr2/lib/xhr2.js:468:24)
    at _stream_readable.js:908:16
    at Function.module.exports.loopWhile (node_modules/deasync/index.js:57:21)
    at node_modules/deasync/index.js:29:18
    at runTask (truffle.es6:50:5)
    at Object.<anonymous> (truffle.es6:276:14)
    at normalLoader (node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .es6] (node_modules/babel-core/lib/api/register/node.js:216:7)
    at Object.<anonymous> (node_modules/babel/lib/_babel-node.js:144:25)
    at node.js:814:3

```

**Comment by kumavis** [comment]
we resolved this in an epic peer programming sessions we'll tell our grandchildren about
